### PR TITLE
Feat/cusum filter

### PR DESCRIPTION
**Pull request by ngriffiths13**
Mostly my changes, but added a few linting changes that ruff wasn't happy about.

### CODE REVIEW

**Comment by abstractqqq** [comment]
The name cusum is too prone to be confused with cumsum. Maybe cumul_sum is better?

**Comment by ngriffiths13** [comment]
> The name cusum is too prone to be confused with cumsum. Maybe cumul_sum is better?

The paper written calls it the cusum algorithm... Which I agree is unfortunate. What about `cusum_changepoint`?

**Comment by abstractqqq** [comment]
> > The name cusum is too prone to be confused with cumsum. Maybe cumul_sum is better?
> 
> 
> 
> The paper written calls it the cusum algorithm... Which I agree is unfortunate. What about `cusum_changepoint`?

I don't have a very strong opinion on this but the recent trend of Polars renaming groupby to group_by, cumsum to cum_sum make me think that maybe cul_sum is a good choice... I would leave the decision to you though

**Review by topher-lo — APPROVED** [review]

**Comment by topher-lo** [comment]
Merged it in. Can decide to change naming in another PR before next release

**Pull request merged**
